language: objective-c
env: VERBOSE=1
before_script:
    - brew update
    - brew tap homebrew/science
    - brew tap ome/alt file://$(pwd)
    - brew audit Formula/*.rb
script:
    - VERBOSE=1 brew install omero --only-dependencies
