language: objective-c
matrix:
  fast_finish: true
env:
  - FORMULA=zeroc-ice35 BREW_OPTS=--with-python
  - FORMULA=omero BREW_OPTS=--only-dependencies
before_script:
    - brew update
    - brew tap homebrew/science
    - brew audit Formula/*.rb
    - brew tap file:///$(pwd)
script:
    - VERBOSE=1 brew install $FORMULA.rb $BREW_OPTS
    - if [[ $FORMULA != 'omero' ]]; then brew test Formula/$FORMULA.rb; fi
